#!/usr/bin/env node
// assets/fonts/*.woff2  ->  data/fonts.css
//
// The build is one HTML file that has to open over file:// on a phone with
// no network, so a <link> to a font CDN would simply never load. The faces
// are base64'd into a stylesheet instead, and build.mjs drops that in where
// app.html says __FONTS__. Only the latin subsets are shipped -- there is no
// other alphabet anywhere in this app.
//
// Both faces are SIL Open Font License 1.1, which permits this; the licences
// travel with them in assets/fonts/.
//
//   node tools/build-fonts.mjs
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

const FACES = [
  { family: "Silkscreen", weight: 400, file: "silkscreen-400.woff2" },
  { family: "Silkscreen", weight: 700, file: "silkscreen-700.woff2" },
  { family: "VT323", weight: 400, file: "vt323-400.woff2" },
];

const head = `/* Oak's Lab's pixel type, embedded.

   Generated by tools/build-fonts.mjs from assets/fonts -- do not hand-edit.

   Silkscreen  (c) The Silkscreen Project Authors, SIL Open Font License 1.1
               https://fonts.google.com/specimen/Silkscreen
   VT323       (c) The VT323 Project Authors, SIL Open Font License 1.1
               https://fonts.google.com/specimen/VT323

   Silkscreen is the chrome -- titles, tabs, headings, buttons -- where the
   strings are short and the blocky look is the point. VT323 is everything
   with sentences in it, and the Lua the exporter prints: it is monospace, so
   the code stays in its columns, and it stays legible at the sizes this UI
   actually uses. Neither is asked to do the other's job.

   font-display: block, not swap -- a pixel face swapping in after a system
   font has painted moves every label on the page. */
`;

let css = head;
for (const f of FACES) {
  const b64 = (await readFile(join(ROOT, "assets/fonts", f.file))).toString("base64");
  css += `\n@font-face {\n`
    + `  font-family: '${f.family}';\n`
    + `  font-style: normal;\n`
    + `  font-weight: ${f.weight};\n`
    + `  font-display: block;\n`
    + `  src: url(data:font/woff2;base64,${b64}) format('woff2');\n`
    + `}\n`;
}

await writeFile(join(ROOT, "data/fonts.css"), css);
console.log(`data/fonts.css  ${(css.length / 1024).toFixed(0)} KB  (${FACES.length} faces)`);
