#!/usr/bin/env node
// Pulls every piece of UI copy (headings, hints, labels, warnings -- every
// string/template child of an el(...) call) out of src/*.js into one plain
// file meant to be hand-edited: copy.md.
//
// Workflow:
//   node tools/extract-copy.mjs        writes copy.md
//   ... edit copy.md by hand, reword whatever you like, save it ...
//   node tools/apply-copy.mjs          preview which lines changed
//   node tools/apply-copy.mjs --apply  write the changes into src/*.js
//
// copy.md is a working file, not a source of truth -- src/*.js stays the
// source of truth. Re-running extract-copy.mjs regenerates it fresh, so
// don't keep hand-written notes in it that aren't copy text.
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { extractCopy } from "./copy-lib.mjs";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const SOURCES = ["src/core.js", "src/script.js", "src/map.js", "src/wizard.js", "src/npc.js", "src/mon.js", "src/move.js", "src/sprite.js", "src/cry.js", "src/ui.js"];

export async function extractAll() {
  const byFile = [];
  for (const file of SOURCES) {
    const src = await readFile(join(ROOT, file), "utf8");
    const entries = extractCopy(file, src);
    if (entries.length) byFile.push({ file, entries });
  }
  return byFile;
}

function render(byFile) {
  const lines = [
    "<!-- Oak's Lab UI copy. Edit the text under each [id] line -- reword, retitle, fix",
    "     typos, whatever. Leave the [id] line itself alone; that is how the edits find",
    "     their way back. When you are done, ask Claude to apply copy.md, or run:",
    "       node tools/apply-copy.mjs         (preview)",
    "       node tools/apply-copy.mjs --apply (write it into src/*.js)",
    "     This file is regenerated by extract-copy.mjs -- it is a worksheet, not a",
    "     record. A `${...}` inside a line is a live value (a count, a name); keep it",
    "     word-for-word or the apply step will skip that one and tell you why. Keep",
    "     each entry on one line -- wrapping it across several adds real line breaks",
    "     to the text in the code, which is usually not what you want. -->",
    "",
  ];
  for (const { file, entries } of byFile) {
    lines.push(`## ${file}`, "");
    for (const e of entries) {
      lines.push(`### [${e.id}] <${e.tag}>`, e.text, "");
    }
  }
  return lines.join("\n");
}

if (process.argv[1]?.endsWith("extract-copy.mjs")) {
  const byFile = await extractAll();
  const total = byFile.reduce((n, f) => n + f.entries.length, 0);
  await writeFile(join(ROOT, "copy.md"), render(byFile), "utf8");
  console.log(`copy.md  ${total} entries across ${byFile.length} files`);
}
